apiVersion: v1
kind: Service
metadata:
  name: {{ include "dockhand-lru-registry.name" . }}
  labels:
    {{- include "dockhand-lru-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: cache
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: cache
  selector:
    {{- include "dockhand-lru-registry.selectorLabels" . | nindent 4 }}
